{
 "title": "Cosmos Validator V2",
 "description": "Dashboard to monitor cosmos validator",
 "tags": [
  "cosmos",
  "blockchain",
  "validator"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "query_validator",
    "query": "SSC 01node : sagavaloper1vpfntljmldpff8l6e8wdf74qgxyku4yq62reep, SSC marblex : sagavaloper1ye6704km459dsu09rhp68xyhd8u3wwfx62r3xy, SSC chandra : sagavaloper106y6thy7gphzrsqq443hl69vfdvntgz2rcxrw2, SSC omnistake : sagavaloper1jc8lmgxwrt8dqn6d9tsfs7v0grk2kg9x0vp3n0, SSC A41 : sagavaloper10jt79knclzrn70dm57ta9vcwry2dwg2y852r2k, SSC Cosmostation : sagavaloper1x5wgh6vwye60wv3dtshs9dmqggwfx2ldrcrgpc, SSC Enigma : sagavaloper14ptc5fd8m3u777rjvyk3nvhx5dfe73835kq2e5, SSC Golden Ratio Staking : sagavaloper1wkjnm4slepltcly74kx4g7pn3x6knwzq2rydyl, SSC Lavender Five : sagavaloper14qekdkj2nmmwea4ufg9n002a3pud23y84606u8, SSC Luganodes : sagavaloper1m9e39ut4gu5c2j0eszhqr4cm6nwxv6hn9g75fk, SSC SG-1 : sagavaloper10f7jk2utqe07p62stg40apef8ylsgpw3cn9cpm, SSC Simply Staking : sagavaloper1qejlpvtz3jnwqa98vuz2laecw00k0jx0wk49gj, SSC Stakecito : sagavaloper1x72h6l0carym5w8wt4ktcjztjy4gere87835e3, SSC StakingCabin : sagavaloper1cxde2pxgkqnndnlzdrkxjungnw7znk29rld40g, SSC ValidationCloud : sagavaloper1qkqjre75w20erffgl3j3t6gkcsejyt0uue95z8, SSC HashQuark : sagavaloper1l320gzp8p08tx4rs0fgqd0e4epegwud2708f3m, SSC Liquify : sagavaloper1asfnpjjw56phtcjl6q2nxcp90lrsuj4u8365af, SSC Stakin : sagavaloper14ptjm2lxqhf7mr6h2c450q78caxzd3njcdts9q, SSC strangelove : sagavaloper1qp5vg3yj54ppgwtrs9xv7qzt97xegc880yl9g5, SSC p2p-org : sagavaloper1u4ks3jtyzgnrjm3dw62apa25h0vk50sgqjac8h"
   }
  ]
 },
 "panels": [
  {
   "title": "Validator health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "options": {
    "content": "\r\n<table style=\"width:100%; height:100%;border:0px solid black;\">\r\n     <td style=\"text-align: center;vertical-align: middle;border:0px solid black; \"><center><img width=\"300px\" src=\"https://github.com/sagaxyz/ssc/blob/main/assets/SAGA_WORDMARK_BLACK.png?raw=true\" /></td>\r\n</table>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cosmos_validator_active{job=\"Validator extra stats\", address=\"$query_validator\"}"
    }
   ]
  },
  {
   "title": "Connected peers",
   "type": "stat",
   "description": "Number of peers node's connected to\n\n(Need to change Threshold)",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cometbft_p2p_peers{job=\"${query_validator:text}\"}"
    }
   ]
  },
  {
   "title": "Missed blocks",
   "type": "stat",
   "description": "Number of missed blocks",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_validator_missed_blocks{job=\"${query_validator:text}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Missed blocks",
   "type": "timeseries",
   "description": "Validator missed blocks",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cosmos_validator_missed_blocks{job=\"Validator extra stats\", address=\"$query_validator\"}"
    }
   ]
  },
  {
   "title": "Syncing",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_state_syncing{job=\"${query_validator:text}\"}"
    }
   ]
  },
  {
   "title": "Chain health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Block height",
   "type": "stat",
   "description": "Height of the chain",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_height{job=\"${query_validator:text}\"}"
    }
   ]
  },
  {
   "title": "Online validators",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_validators-cometbft_consensus_missing_validators{job=\"${query_validator:text}\"}"
    }
   ]
  },
  {
   "title": "Offline validators",
   "type": "stat",
   "description": "Number of validators who did not sign",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_missing_validators{job=\"${query_validator:text}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Confirmed Tx",
   "type": "stat",
   "description": "Total number of transactions committed",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_total_txs{job=\"${query_validator:text}\"}"
    }
   ]
  },
  {
   "title": "Validators missing blocks",
   "type": "stat",
   "description": "Number of validators missing blocks",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(cosmos_validators_missed_blocks{job=\"validators\"} > 0) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Top validators missing blocks",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 10 },
   "targets": [
    {
     "expr": "sort_desc(topk(10, cosmos_validator_missed_blocks{job=\"Validator extra stats\"})) > 0"
    }
   ]
  },
  {
   "title": "Total bonded tokens",
   "type": "stat",
   "description": "The total number of bonded tokens in the network",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_validators_power{job=\"${query_validator:text}\"}"
    }
   ]
  },
  {
   "title": "Offline: bonded tokens",
   "type": "stat",
   "description": "Total voting power of the missing validators",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_missing_validators_power{job=\"${query_validator:text}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Offline: voting power %",
   "type": "stat",
   "description": "Total voting power of the missing validators",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(cometbft_consensus_missing_validators_power{job=\"${query_validator:text}\"} / cometbft_consensus_validators_power{job=\"${query_validator:text}\"})"
    }
   ]
  },
  {
   "title": "Unconfirmed Tx",
   "type": "stat",
   "description": "Number of uncommitted transactions",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cometbft_mempool_size{job=\"${query_validator:text}\"}"
    }
   ]
  },
  {
   "title": "Top missed blocks",
   "type": "stat",
   "description": "Number of highest missed blocks for validators on chain",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(cosmos_validator_missed_blocks{job=\"Validator extra stats\", address!=\"sagavaloper1s3960ghrds6vf09mu4wtmj3l3puxd4mgr4zcm9\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blocks per minute",
   "type": "stat",
   "description": "Number of blocks produced last minute",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "round(increase(cometbft_consensus_height{job=\"${query_validator:text}\"}[1m]))"
    }
   ]
  },
  {
   "title": "Blocks per minute",
   "type": "timeseries",
   "description": "Number of block produced last minute",
   "gridPos": { "h": 8, "w": 9, "x": 3, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(cometbft_consensus_height{job=\"${query_validator:text}\"}[1m])"
    }
   ]
  },
  {
   "title": "Block Size (bytes)",
   "type": "timeseries",
   "description": "Block size in bytes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "cometbft_consensus_block_size_bytes{job=\"${query_validator:text}\"}"
    }
   ]
  },
  {
   "title": "Validator stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Jailed",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cosmos_validator_jailed{job=\"Validator extra stats\", address=\"$query_validator\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rank",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(cosmos_validator_rank{job=\"Validator extra stats\", address=\"$query_validator\"})",
     "legendFormat": "{{ moniker }}"
    }
   ]
  },
  {
   "title": "Total delegations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cosmos_validator_delegations{job=\"Validator extra stats\", address=\"$query_validator\"}) by (denom)",
     "legendFormat": "{{ denom }}"
    }
   ]
  },
  {
   "title": "Commission rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cosmos_validator_commission_rate{job=\"Validator extra stats\", address=\"$query_validator\"}"
    }
   ]
  },
  {
   "title": "Delegations count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(cosmos_validator_delegations{job=\"Validator extra stats\", address=\"$query_validator\"})",
     "legendFormat": "{{ moniker }}"
    }
   ]
  },
  {
   "title": "Redelegations count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(cosmos_validator_redelegations{job=\"Validator extra stats\", address=\"$query_validator\"}) OR on() vector(0)",
     "legendFormat": "{{ moniker }}"
    }
   ]
  },
  {
   "title": "Unbondings count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(cosmos_validator_unbondings{job=\"Validator extra stats\", address=\"$query_validator\"}) OR on() vector(0)",
     "legendFormat": "{{ moniker }}"
    }
   ]
  },
  {
   "title": "Delegations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum(cosmos_validator_delegations{job=\"Validator extra stats\", address=\"$query_validator\"}) by (moniker, denom)",
     "legendFormat": "{{ moniker }}, {{ denom }}"
    }
   ]
  },
  {
   "title": "Delegations",
   "type": "table",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "cosmos_validator_delegations{job=\"Validator extra stats\", address=\"$query_validator\"}"
    }
   ]
  },
  {
   "title": "Redelegations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cosmos_validator_redelegations{job=\"Validator extra stats\", address=\"$query_validator\"}) by (moniker, denom)",
     "legendFormat": "{{ moniker }}, {{ denom }}"
    }
   ]
  },
  {
   "title": "Redelegations",
   "type": "table",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 38 },
   "targets": [
    {
     "expr": "cosmos_validator_redelegations{job=\"Validator extra stats\", address=\"$query_validator\"} "
    }
   ]
  },
  {
   "title": "Unbondings",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cosmos_validator_unbondings{job=\"Validator extra stats\", address=\"$query_validator\"}) by (moniker, denom)",
     "legendFormat": "{{ moniker }}, {{ denom }}"
    }
   ]
  },
  {
   "title": "Unbondings",
   "type": "table",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 45 },
   "targets": [
    {
     "expr": "cosmos_validator_unbondings{job=\"Validator extra stats\", address=\"$query_validator\"} "
    }
   ]
  },
  {
   "title": "Rewards",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cosmos_validator_rewards{job=\"Validator extra stats\", address=\"$query_validator\"}",
     "legendFormat": "{{ moniker }}, {{ denom }}"
    }
   ]
  },
  {
   "title": "Commission",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "cosmos_validator_commission{job=\"Validator extra stats\", address=\"$query_validator\"}",
     "legendFormat": "{{ moniker }}, {{ denom }}"
    }
   ]
  }
 ]
}