{
 "title": "Overview dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "query_validator",
    "label": "Validator",
    "query": "SSC 01node, SSC marblex, SSC chandra, SSC omnistake, SSC A41, SSC Cosmostation, SSC Enigma, SSC Golden Ratio Staking, SSC Lavender Five, SSC Luganodes, SSC SG-1, SSC Simply Staking, SSC Stakecito, SSC StakingCabin, SSC ValidationCloud, SSC HashQuark, SSC Liquify, SSC Stakin, SSC strangelove, SSC p2p-org"
   }
  ]
 },
 "panels": [
  {
   "title": "Total power of all validators",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "cometbft_consensus_validators_power{job=\"$query_validator\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Amount of validators",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "cometbft_consensus_validators{job=\"$query_validator\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validator power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "cometbft_consensus_validator_power{job=\"$query_validator\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Missing validators",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "cometbft_consensus_missing_validators{job=\"$query_validator\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blocks per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(cometbft_consensus_block_interval_seconds_count{job=\"$query_validator\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consensus height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "cometbft_consensus_height{job=\"$query_validator\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"$query_validator\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap inuse bytes (MiB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"$query_validator\"} / 1048576",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}