{
 "title": "Relayer dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Osmosis chain height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "cosmos_relayer_chain_latest_height{job=\"Relayer\", chain=\"osmo-test-5\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Osmosis wallet balance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "cosmos_relayer_wallet_balance{job=\"Relayer\", chain=\"osmo-test-5\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pegasus chain height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "cosmos_relayer_chain_latest_height{chain=\"pegasus-1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client expiration time (min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "cosmos_relayer_client_expiration_seconds / 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Relayer is up",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "up{job=\"Relayer\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block query errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "cosmos_relayer_block_query_errors_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Amount of observed packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(cosmos_relayer_observed_packets{job=\"Relayer\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Trusting period (min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "cosmos_relayer_client_trusting_period_seconds / 60",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}