{
 "title": "SSC overview",
 "description": "Dashboard to monitor cosmos validator",
 "tags": [
  "cosmos",
  "blockchain",
  "validator"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "\r\n<table style=\"width:100%; height:100%;border:0px solid black;\">\r\n     <td style=\"text-align: center;vertical-align: middle;border:0px solid black; \"><center><img width=\"300px\" src=\"https://github.com/sagaxyz/ssc/blob/main/assets/SAGA_WORDMARK_BLACK.png?raw=true\" /></td>\r\n</table>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active validators",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(cosmos_validators_active)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Jailed validators",
   "type": "stat",
   "description": "Number of jailed validators",
   "gridPos": { "h": 8, "w": 3, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(cosmos_validators_jailed{address!=\"sagavaloper1s3960ghrds6vf09mu4wtmj3l3puxd4mgr4zcm9\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total missed blocks",
   "type": "stat",
   "description": "Number of missed blocks by all validators",
   "gridPos": { "h": 8, "w": 3, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(cosmos_validators_missed_blocks{job=\"validators\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validators missing blocks",
   "type": "stat",
   "description": "Number of validators missing blocks",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(cosmos_validators_missed_blocks{job=\"validators\"} > 0) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Top validators missing blocks",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sort_desc(topk(10, cosmos_validator_missed_blocks{job=\"Validator extra stats\"})) > 0",
     "legendFormat": "{{moniker}}"
    }
   ]
  },
  {
   "title": "Top missed blocks",
   "type": "stat",
   "description": "Number of highest missed blocks for validators on chain",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(cosmos_validator_missed_blocks{job=\"Validator extra stats\", address!=\"sagavaloper1s3960ghrds6vf09mu4wtmj3l3puxd4mgr4zcm9\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redelegations count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(cosmos_validator_redelegations{job=\"Validator extra stats\"}) OR on() vector(0)",
     "legendFormat": "{{ moniker }}"
    }
   ]
  },
  {
   "title": "Total bonded tokens",
   "type": "stat",
   "description": "The total number of bonded tokens in the network",
   "gridPos": { "h": 6, "w": 4, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_validators_power{job=\"summary SSC\"}"
    }
   ]
  },
  {
   "title": "Blocks per minute",
   "type": "stat",
   "description": "Number of blocks produced last minute",
   "gridPos": { "h": 6, "w": 3, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "round(increase(cometbft_consensus_height{job=\"summary SSC\"}[1m]))"
    }
   ]
  },
  {
   "title": "Blocks per minute",
   "type": "timeseries",
   "description": "Number of block produced last minute",
   "gridPos": { "h": 12, "w": 6, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(cometbft_consensus_height{job=\"summary SSC\"}[1m])"
    }
   ]
  },
  {
   "title": "Commission rate",
   "type": "piechart",
   "gridPos": { "h": 23, "w": 8, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cosmos_validator_commission_rate{job=\"Validator extra stats\"}",
     "legendFormat": "{{moniker}}"
    }
   ]
  },
  {
   "title": "Unbondings count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(cosmos_validator_unbondings{job=\"Validator extra stats\"}) OR on() vector(0)",
     "legendFormat": "{{ moniker }}"
    }
   ]
  },
  {
   "title": "Delegations count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 3, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(cosmos_validator_delegations{job=\"Validator extra stats\"})",
     "legendFormat": "{{ moniker }}"
    }
   ]
  },
  {
   "title": "Offline: voting power %",
   "type": "stat",
   "description": "Total voting power of the missing validators",
   "gridPos": { "h": 6, "w": 3, "x": 7, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(cometbft_consensus_missing_validators_power{job=\"summary SSC\"} / cometbft_consensus_validators_power{job=\"summary SSC\"})"
    }
   ]
  },
  {
   "title": "Block height",
   "type": "stat",
   "description": "Height of the chain",
   "gridPos": { "h": 11, "w": 3, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_height{job=\"summary SSC\"}"
    }
   ]
  },
  {
   "title": "Total delegations",
   "type": "stat",
   "gridPos": { "h": 11, "w": 4, "x": 3, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cosmos_validator_delegations{job=\"Validator extra stats\"}) by (denom)",
     "legendFormat": "{{ denom }}"
    }
   ]
  },
  {
   "title": "Offline: bonded tokens",
   "type": "stat",
   "description": "Total voting power of the missing validators",
   "gridPos": { "h": 11, "w": 3, "x": 7, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_missing_validators_power{job=\"summary SSC\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Size (bytes)",
   "type": "timeseries",
   "description": "Block size in bytes",
   "gridPos": { "h": 11, "w": 6, "x": 10, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "cometbft_consensus_block_size_bytes{job=\"summary SSC\"}"
    }
   ]
  }
 ]
}