name: Push to Docker Hub

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Git fetch everything
        run: git fetch --prune --unshallow

      - name: Get Github tag
        id: meta
        run: |
          echo "::set-output name=tag::$(echo ${{github.ref_name}} | sed -e 's/^v//')"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: deploy/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: sagaxyz/cosmos-exporter:${{ steps.meta.outputs.tag }}, sagaxyz/cosmos-exporter:latest